### ISSUE TITLE
app/members/views.py & app/members/apis.py 가 분리된 이유?

### ISSUE THREAD

**Issue by AsheKR** [jeonyh0924/WPS_DabangAPI#1]
views.py 는 보통 Django template 을 Rendering 할 때 쓰고
apis.py 는 rest API 를 작성할 때 사용합니다.

지금은  코드가 좀 섞여있는 것 같습니다. 수정부탁드립니다

**Comment by jeonyh0924** [comment]
확인하였습니다!

**Comment by jeonyh0924** [comment]
이해하기 쉽게 말씀해주셔서 감사합니다~~
