### ISSUE TITLE
Unreachable Code

### ISSUE THREAD

**Issue by AsheKR** [jeonyh0924/WPS_DabangAPI#2]
https://github.com/jeonyh0924/WPS_DabangAPI/blob/a56a5569ee941196e7790142284eaff70e5a2dc3/app/members/views.py#L38

https://github.com/jeonyh0924/WPS_DabangAPI/blob/a56a5569ee941196e7790142284eaff70e5a2dc3/app/members/views.py#L52

위 두 코드는 어느 상황에서도 실행될 수 없습니다.

**Comment by jeonyh0924** [comment]
ㅎㅎㅎ 민망합니다...
제가 생각에는 기존에 지원해주는 메서드를 사용하는거여서 나중에 유지보수를 할 수 있게
함수안에 super를 써서 코드 안에 제 코드를 넣는다는 걸 저렇게 해버렸네요..

저건 나중에 추가적으로 수정하여 제 의도대로 동작할 수 있도록 수정하겠습니다!!
