### ISSUE TITLE
Authenticate 방법을 다르게 사용해야합니다.

### ISSUE THREAD

**Issue by AsheKR** [jeonyh0924/WPS_DabangAPI#3]
https://github.com/jeonyh0924/WPS_DabangAPI/blob/a56a5569ee941196e7790142284eaff70e5a2dc3/app/members/views.py#L55

이렇게 사용하면 안됩니다.

모든 API에서 JWT 를 사용한다면
https://www.django-rest-framework.org/api-guide/authentication/#setting-the-authentication-scheme

`DEFAULT_AUTHENTICATION_CLASSES` 속성에 기본 인증을 추가하여야하고

특정 API 에서 JWT 를 사용한다면
View의 authentication_classes 속성에 넣어야합니다

**Comment by jeonyh0924** [comment]
ㅎㅎㅎ 민망합니다. 제가 디테일이 부족했네요, 여러 get_기능들을 써보고 싶었다는 변명이 있습니다 ㅎㅎㅎㅎ.... 수정할게요!!
- settings에 이미 디폴트로 했어서 get_authenticate_header만 수정했습니당
