### ISSUE TITLE
잘못된 코드 수정

### ISSUE THREAD

**Issue by AsheKR** [jeonyh0924/WPS_DabangAPI#4]
https://github.com/jeonyh0924/WPS_DabangAPI/blob/a56a5569ee941196e7790142284eaff70e5a2dc3/app/members/serializers.py#L27-L29

**Comment by jeonyh0924** [comment]
1. 이게 viewset에 permission을 지정해주는 것 보다 
serializer에 지정을 하는것이 더 올바른 코드인가요?
serializer 와 api에서 해주어야할 역할의 개념이 아직 확실히 정립되지 않아서 질문드립니다.

2. 강사님이 현재 수강생 분들에게 serializer에서 할 수 있는 기능들이 더 많다고 api에서 다 짜도 돌아가지만 serializer에서 해줄 수 있는 부분도 많다고 말씀을 하셨다고 하더라구요, 
 - 앞으로 그럼 serializer에서 할 수 있는 부분들은 serializer에서 충분히 다 하고 serializer가 할 수 없는 부분들을 api에서 한다고 생각을 하고 코드를 구성해보는게 더 낫겠죠??

3. 작성해주신 코드로 수정하였습니다!

**Comment by AsheKR** [comment]
해당 이슈는 Serializer 에 저 코드가 존재해서 발생한 문제입니다. 저 코드는 View에만 들어가 있어야만합니다.

Serializer 와 View 의 차이를 어떻게 설명하면 좋을지 모르겠네요

1. Serializer

이름 그대로 해석해보면 아래와 같은 동작을 합니다.
파이썬 객체를 HTTP 로 전송할 수 있게 만들거나( serialize )
HTTP 로 넘어온 데이터를 파이썬 객체로 만들어서 사용할 수 있게 합니다.( deserialize )

1.1 serialize

**Comment by AsheKR** [comment]
해당 이슈는 Serializer 에 저 코드가 존재해서 발생한 문제입니다. 저 코드는 View에만 들어가 있어야만합니다.

Serializer 와 View 의 차이를 어떻게 설명하면 좋을지 모르겠네요

1. Serializer

이름 그대로 해석해보면 아래와 같은 동작을 합니다.
파이썬 객체를 HTTP 로 전송할 수 있게 만들거나( serialize )
HTTP 로 넘어온 데이터를 파이썬 객체로 만들어서 사용할 수 있게 합니다.( deserialize )

1.1 serialize

파이썬 객체(ORM 으로 뽑은 데이터)를 HTTP 형태로 만들 때 어떤 형태로 만들지에 대한 것입니다.

**Comment by AsheKR** [comment]
해당 이슈는 Serializer 에 저 코드가 존재해서 발생한 문제입니다. 저 코드는 View에만 들어가 있어야만합니다.

Serializer 와 View 의 차이를 어떻게 설명하면 좋을지 모르겠네요.

1. Serializer

Serializer 는 데이터를 어떻게 처리하고 보여주어야할까가 주 목적입니다.

이름 그대로 해석해보면 아래와 같은 동작을 합니다.
파이썬 객체를 HTTP 로 전송할 수 있게 만들거나( serialize )
HTTP 로 넘어온 데이터를 파이썬 객체로 만들어서 사용할 수 있게 합니다.( deserialize )

간단하게 요약하자면 **ORM으로 가져온 데이터를 사용하는 로직은 Serializer 에 있어야합니다.**


2. View

View 는 요청에 대한 처리를 어떻게 할 것인가가 주요 목적입니다.
인증은 어떻게? 권한은 어떻게? 어떤 형식으로 받나? 어떤 형식으로 보여줘야하나? 페이징 처리하나? 등등..

위 내용으로 이해가되지 않으면 사용해보면서 감을 익혀야할 것 같습니다.
저도 찾아보고있는데 명확한 설명을 찾지 못하겠네요..
